version: "3.6"
services:
  anime-list-app:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "3000:3000"
    volumes:
      - .:/app 
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_OPTIONS=--openssl-legacy-provider